"""initial_schema

Revision ID: 4315ef48ed96
Revises: 
Create Date: 2026-05-15 23:30:14.212709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4315ef48ed96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre_corto', sa.String(), nullable=False),
    sa.Column('poblacion', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('kanban_column', sa.String(), nullable=False),
    sa.Column('color_estado', sa.String(), nullable=False),
    sa.Column('prioridad', sa.String(), nullable=False),
    sa.Column('comercial', sa.String(), nullable=True),
    sa.Column('tecnico_estudios', sa.String(), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('aging_dias', sa.Integer(), nullable=True),
    sa.Column('oferta', sa.Float(), nullable=True),
    sa.Column('estudio_direccion', sa.Text(), nullable=True),
    sa.Column('presupuesto', sa.Text(), nullable=True),
    sa.Column('contactos', sa.Text(), nullable=True),
    sa.Column('actuaciones', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_codigo'), 'solicitudes', ['codigo'], unique=False)
    op.create_index(op.f('ix_solicitudes_comercial'), 'solicitudes', ['comercial'], unique=False)
    op.create_index(op.f('ix_solicitudes_estado'), 'solicitudes', ['estado'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_solicitudes_estado'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_comercial'), table_name='solicitudes')
    op.drop_index(op.f('ix_solicitudes_codigo'), table_name='solicitudes')
    op.drop_table('solicitudes')
    # ### end Alembic commands ###

